# Generated by Django 5.1.6 on 2025-03-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_department_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='company',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_led', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель компании'),
        ),
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отдела'),
        ),
    ]
