# Generated by Django 5.1.6 on 2025-03-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('users', '0003_alter_department_options_company_founded_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_for_companys', to='users.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='survey',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_for_department', to='users.department', verbose_name='Отдел'),
        ),
    ]
